APPEND_ASSEMBLED = "append_assembled"
CHECK_FOR_WARNINGS = "check_for_warnings"

COLUMN_COUNTS = "column_counts"
COLUMN_DICTIONARY = "column_dictionary"
COLUMN_INDICES = "column_indices"
COLUMN_LIST = "column_list"
COLUMN_NAMES = "column_names"
COLUMN_NAMES_TABLE = "column_names_table"
COLUMN_POSTFIX = "_column"
COLUMN_PREFIX_DICTIONARY = "column_prefix_dictionary"

COLUMNS_CATEGORICAL = "columns_categorical"
COLUMNS_DISPLAY_NAME = "columns_display_name"
COLUMNS_FILE = "columns_file"
COLUMNS_INFO = "columns_info"
COLUMNS_PATH = "columns_path"
COLUMNS_SKIP = "columns_skip"
COLUMNS_VALUE = "columns_value"

COMMAND = "command"
COMMAND_ASSEMBLE = "assemble"
COMMAND_CHECK_QUALITY = "check_quality"
COMMAND_COMPARE_SCHEMAS = "compare_schemas"
COMMAND_CONVERT_SCHEMA = "convert_schema"
COMMAND_GENERATE_SIDECAR = "generate_sidecar"
COMMAND_EXTRACT_SPREADSHEET = "extract_spreadsheet"
COMMAND_MERGE_SPREADSHEET = "merge_spreadsheet"
COMMAND_OPTION = "command_option"
COMMAND_REMAP = "remap"
COMMAND_REMODEL = "remodel"
COMMAND_SEARCH = "search"
COMMAND_TARGET = "command_target"
COMMAND_TO_LONG = "to_long"
COMMAND_TO_SHORT = "to_short"
COMMAND_VALIDATE = "validate"

DEFINITION_FILE = "definition_file"
DEFINITIONS = "definitions"
DEFINITION_STRING = "definition_string"
DOWNLOAD_FILE = "download_file"

EVENTS = "events"
EVENTS_DISPLAY_NAME = "events_display_name"
EVENTS_FILE = "events_file"
EVENTS_FLASH = "events_flash"
EVENTS_PATH = "events_path"
EVENTS_STRING = "events_string"
EVENTS_SUBMIT = "events_submit"
EVENTS_SUBMIT_FLASH = "events_submit_flash"

EXPAND_DEFS = "expand_defs"

FILE_LIST = "file_list"
FORMAT_OPTION = "format_option"
FORMAT_TO_EXCEL = "to_excel"
FORMAT_TO_JSON = "to_json"
FORMAT_TO_TSV = "to_tsv"
FROM_FORM = "from_form"
FROM_SERVICE = "from_service"

HAS_COLUMN_NAMES = "has_column_names"

INCLUDE_CONTEXT = "include_context"
INCLUDE_DEFINITION_TAGS = "include_definition_tags"
INCLUDE_DESCRIPTION_TAGS = "include_description_tags"
INCLUDE_SUMMARIES = "include_summaries"
ISSUE_STRING = "issue_string"

LIMIT_ERRORS = "limit_errors"

MSG = "msg"
MSG_CATEGORY = "msg_category"
OTHER_VERSION_OPTION = "Other"
OUTPUT_DISPLAY_NAME = "output_display_name"

QUERIES = "queries"
QUERY_INPUT = "query_input"
QUERY_NAMES = "query_names"

REMODEL_FILE = "remodel_file"
REMODEL_OPERATIONS = "remodel_operations"
REMODEL_STRING = "remodel_string"
REMOVE_DEFS = "remove_defs"
REMOVE_TYPES = "remove_types"
REMOVE_TYPES_ON = "remove_types_on"
REPLACE_DEFS = "replace_defs"
REQUEST_TYPE = "request_type"
REQUIRED_COLUMN_INDICES = "required_column_indices"

# Schema-specific constants
SCHEMA = "schema"
SCHEMA_FORM = "schema_form"
SCHEMA_DISPLAY_NAME = "schema_display_name"
SCHEMA_FILE = "schema_file"
SCHEMA_FILE_FLASH = "schema_file_flash"
SCHEMA_FILE_OPTION = "schema_file_option"
SCHEMA_FOLDER_OPTION = "schema_folder_option"
SCHEMA_FORMAT = "schema_format"
SCHEMA_PATH = "schema_path"
SCHEMA_SELECT_FLASH = "schema_select_flash"
SCHEMA_STRING = "schema_string"
SCHEMA_SUBMIT = "schema_submit"
SCHEMA_SUBMIT_FLASH = "schema_submit_flash"
SCHEMA_UPLOAD_OPTIONS = "schema_upload_options"
SCHEMA_URL = "schema_url"
SCHEMA_URL_DISPLAY_NAME = "schema_url_display_name"
SCHEMA_URL_FLASH = "schema_url_flash"
SCHEMA_URL_OPTION = "schema_url_option"
SCHEMA_VERSION = "schema_version"
SCHEMA_VERSION_LIST = "schema_version_list"
SCHEMA_VERSION_STRING = "schema_version_string"

SCHEMA1 = "schema"
SCHEMA2 = "schema2"
SECOND_SCHEMA_DISPLAY_NAME = "second_schema_display_name"
SECOND_SCHEMA_FILE = "second_schema_file"
SECOND_SCHEMA_FILE_OPTION = "second_schema_file_option"
SECOND_SCHEMA_FOLDER_OPTION = "second_schema_folder_option"
SECOND_SCHEMA_FORMAT = "second_schema_format"
SECOND_SCHEMA_UPLOAD_OPTIONS = "second_schema_upload_options"
SECOND_SCHEMA_URL = "second_schema_url"
SECOND_SCHEMA_URL_OPTION = "second_schema_url_option"

SERVICE = "service"
SERVICE_PARAMETERS = "service_parameters"

SHOW_DETAILS = "show_details"
SIDECAR = "sidecar"
SIDECAR_FILE = "sidecar_file"
SIDECAR_PATH = "sidecar_path"
SIDECAR_STRING = "sidecar_string"

SPREADSHEET = "spreadsheet"
SPREADSHEET_DISPLAY_NAME = "spreadsheet_display_name"
SPREADSHEET_FILE = "spreadsheet_file"
SPREADSHEET_FLASH = "spreadsheet_flash"
SPREADSHEET_ORIGINAL_FILE = "spreadsheet_original_file"
SPREADSHEET_PATH = "spreadsheet_path"
SPREADSHEET_STRING = "spreadsheet_string"
SPREADSHEET_TYPE = "spreadsheet_type"
SPREADSHEET_SUBMIT_FLASH = "spreadsheet_submit_flash"

STRING_INPUT = "string_input"
STRING_LIST = "string_list"
STRING_RESULT = "string_result"

TAG_COLUMNS = "tag_columns"
WORKSHEET = "worksheet"
WORKSHEET_NAME = "worksheet_name"
WORKSHEET_NAMES = "worksheet_names"
WORKSHEET_SELECT = "worksheet_select"
WORKSHEET_SELECTED = "worksheet_selected"
ZIP_NAME = "zip_name"

# Type constants
BOOLEAN = "boolean"
STRING = "string"
