CHECK_FOR_WARNINGS = 'check-for-warnings'

COMMAND = 'command'
COMMAND_ASSEMBLE = 'assemble'
COMMAND_TO_LONG = 'to_long'
COMMAND_TO_SHORT = 'to_short'
COMMAND_VALIDATE = 'validate'

COLUMN_NAMES = 'column-names'
COLUMN_NAMES_TABLE = 'column-names-table'
COLUMN_POSTFIX = '-column'
COLUMN_PREFIX_DICTIONARY = 'column-prefix-dictionary'
COLUMNS_FILE = 'columns-file'
COLUMNS_PATH = 'columns-path'
COLUMNS_DISPLAY_NAME = 'columns-display-name'

DISPLAY_NAME = 'display_name'
HAS_COLUMN_NAMES = 'has-column-names'
TAG_COLUMNS = 'tag-columns'
TAG_COLUMN_INDICES = 'tag-column-indices'

DOWNLOAD_FILE = 'download-file'

ERROR_COUNT = 'error-count'
EVENTS_DISPLAY_NAME = 'events-display-name'
EVENTS_FILE = 'events-file'
EVENTS_FLASH = 'events-flash'
EVENTS_PATH = 'events-path'
EVENTS_SUBMIT = 'events-submit'
EVENTS_SUBMIT_FLASH = 'events-submit-flash'

HED_DISPLAY_NAME = 'hed_display_name'
HED_MAJOR_VERSIONS = 'hed-major-versions'
HED_OPTION = 'hed-option'
HED_OPTION_ASSEMBLE = 'hed-option-assemble'
HED_OPTION_TO_LONG = 'hed-option-to-long'
HED_OPTION_TO_SHORT = 'hed-option-to-short'
HED_OPTION_VALIDATE = 'hed-option-validate'
HED_OTHER_VERSION = 'hed-other-version'
HED_OTHER_VERSION_OPTION = 'Other'
HED_SCHEMA_FILE = 'hed_schema_file'
HED_SCHEMA_PATH = 'hed-schema-path'
HED_SCHEMA_URL = 'hed-schema-url'
HED_SELECT_FLASH = 'hed-select-flash'
HEDSTRING = 'hedstring'
HEDSTRING_LIST = 'hedstring_list'
HED_VERSION = 'hed_version'
HED_XML_FILE = 'hed_xml_file'

JSON_DICTIONARY = 'json_dictionary'
JSON_DISPLAY_NAME = 'json_display_name'
JSON_FILE = 'json_file'
JSON_PATH = 'json_path'
JSON_STRING = 'json_string'
JSON_STRINGS = 'json_strings'

REQUIRED_TAG_COLUMN_INDICES = 'required-tag-column-indices'
SPREADSHEET_DISPLAY_NAME = 'spreadsheet-display-name'
SPREADSHEET_FILE = 'spreadsheet-file'
SPREADSHEET_PATH = 'spreadsheet-path'

WARNING_COUNT = 'warning-count'

WORKSHEET_NAME = 'worksheet-name'
WORKSHEET_NAMES = 'worksheet-names'
WORKSHEET_SELECT = 'worksheet-select'
WORKSHEET_SELECTED = 'worksheet-selected'

# Schema-specific constants
SCHEMA_FORM = 'schema-form'
SCHEMA_DISPLAY_NAME = 'schema-display-name'
SCHEMA_FILE = 'schema-file'
SCHEMA_FILE_FLASH = 'schema-file-flash'
SCHEMA_FILE_OPTION = 'schema-file-option'
SCHEMA_OPTION = 'schema-option'
SCHEMA_OPTION_CHECK = 'schema-option-check'
SCHEMA_OPTION_CONVERT = 'schema-option-convert'
SCHEMA_PATH = 'schema-path'
SCHEMA_STRING = 'schema_string'
SCHEMA_SUBMIT = 'schema-submit'
SCHEMA_SUBMIT_FLASH = 'schema-submit-flash'
SCHEMA_UPLOAD_OPTIONS = 'schema-upload-options'
SCHEMA_URL = 'schema-url'
SCHEMA_URL_DISPLAY_NAME = 'schema-url-display-name'
SCHEMA_URL_FLASH = 'schema-url-flash'
SCHEMA_URL_OPTION = 'schema-url-option'

# Type constants
BOOLEAN = 'boolean'
STRING = 'string'
