ADDITIONAL_EXAMPLES_PAGE = 'additional-examples.html'
HED_TOOLS_HELP_PAGE = 'hed-tools-help.html'
HED_TOOLS_HOME_PAGE = 'hed-tools-home.html'
VALIDATION_PAGE = 'validation.html'
EEG_VALIDATION_PAGE = 'eeg-validation.html'
COMMON_ERRORS = 'commonerrors.html'
